#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TAXONOMY_PATH = ROOT / "schemas" / "taxonomy.json"
TAGS_PATH = ROOT / "TryHackMe" / "_meta" / "TAGS.md"
FIELD_TITLES = {
    "domain": "Domain tags",
    "skills": "Skill tags",
    "artifacts": "Artifact tags",
}
FIELD_GUIDANCE = {
    "domain": "Choose the domain values that best describe the note scope.",
    "skills": "Prefer the smallest set of skills that preserves retrieval value.",
    "artifacts": "Use artifact tags to describe note shape rather than subject matter.",
}
HYGIENE_RULES = [
    "Avoid inventing new values unless the taxonomy cannot express the note accurately.",
    "Use `TARGET_IP`, `USER_A`, and `example.com` style placeholders in public notes.",
    "Keep write-ups sanitized; do not publish full exploit chains or copy-paste payload walkthroughs.",
]


def load_taxonomy() -> dict:
    return json.loads(TAXONOMY_PATH.read_text(encoding="utf-8"))


def render_section(name: str, section: dict) -> list[str]:
    allowed = section["allowed"]
    aliases = section.get("aliases", {})

    lines = [f"## {FIELD_TITLES[name]}", ""]
    lines.append(FIELD_GUIDANCE[name])
    lines.append("")
    lines.append(f"_Canonical values: `{len(allowed)}`_")
    lines.append("")
    for value in allowed:
        lines.append(f"- `{value}`")

    if aliases:
        lines.extend(["", "### Aliases", ""])
        for alias, canonical in sorted(aliases.items()):
            lines.append(f"- `{alias}` -> `{canonical}`")

    return lines


def render_tags_doc(taxonomy: dict) -> str:
    lines = [
        "# Tag Taxonomy (TryHackMe)",
        "",
        "Use this page as the controlled-vocabulary reference for TryHackMe note front matter.",
        "",
        "> This file is derived from `schemas/taxonomy.json`.",
        "> Do not edit this file manually; update `schemas/taxonomy.json` and run `python scripts/render_tags_doc.py`.",
        "",
        "> Use a controlled vocabulary.",
        "> Goal: consistent retrieval (GitHub search) and reusable mental models.",
        "> Prefer fewer tags per note when possible.",
        "",
        "## Quick navigation",
        "",
        "- [Metadata hub](README.md)",
        "- [Topic index](INDEX.md)",
        "- [Room template](TEMPLATE_room.md)",
        "- [Taxonomy closure](../../docs/taxonomy-closure.md)",
        "",
        "## How to use this page",
        "",
        "- Use `domain` values for note scope.",
        "- Use `skills` values for concrete retrieval and pattern lookup.",
        "- Use `artifacts` values for note shape.",
        "- Check aliases before inventing a near-duplicate value.",
        "",
    ]

    for field in ("domain", "skills", "artifacts"):
        lines.extend(render_section(field, taxonomy[field]))
        lines.append("")

    lines.extend(["## Hygiene rules", ""])
    for rule in HYGIENE_RULES:
        lines.append(f"- {rule}")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Render TryHackMe/_meta/TAGS.md from schemas/taxonomy.json."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit with status 1 if TAGS.md is not up to date.",
    )
    args = parser.parse_args()

    taxonomy = load_taxonomy()
    rendered = render_tags_doc(taxonomy)

    if args.check:
        existing = TAGS_PATH.read_text(encoding="utf-8") if TAGS_PATH.exists() else ""
        if existing != rendered:
            print(f"{TAGS_PATH.relative_to(ROOT).as_posix()} is out of date.")
            return 1
        print(f"{TAGS_PATH.relative_to(ROOT).as_posix()} is up to date.")
        return 0

    TAGS_PATH.write_text(rendered, encoding="utf-8")
    print(f"Rendered {TAGS_PATH.relative_to(ROOT).as_posix()} from schemas/taxonomy.json.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
